print("Escriba su primer nombre:")
nombre1=input()
print("Escriba su segundo nombre:")
nombre2=input("")
print("Escriba su primer apellido:")
apellido1=input()
print("Escriba su segundo apellido")
apellido2=input()
print("Escriba su edad:")
edad=input()
print("Escriba su año de nacimieno:")
anio=input()
print("Nombre completo:" + nombre1 + "" + nombre2 + "" + apellido1 + "" + apellido2)
print("edad:"+ edad)
print("año de nacimieto:" + anio)
